name: Rust Windows Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        profile: minimal
        override: true

    - name: Build
      run: cargo build --release

    - name: Run tests
      run: cargo test

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-sample-test-executable
        path: target/release/windows_api_example.exe
